# Generated by Django 5.1.3 on 2024-11-23 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CapitalRisque',
            fields=[
                ('id_capital_risque', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('CIN', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('pseudo', models.CharField(max_length=20)),
                ('pwrd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id_achat', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATIONDS1.article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATIONDS1.capitalrisque')),
            ],
        ),
    ]
