# Generated by Django 5.1.3 on 2024-11-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATIONDS1', '0002_avis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avis',
        ),
    ]
